server:
  port: ${port:8000}
  ssl:
    enabled: false
springdoc:
  swagger-ui:
    url: /openapi/backend-api.yaml
spring:
  datasource:
    platform: postgres
    url: ${JDBC_DATABASE_URL}
    initialization-mode: always
  devtools:
    add-properties: false
  flyway:
    baseline-on-migrate: true
