server:
  port: ${PORT:5000}
  ssl:
    enabled: false
springdoc:
  swagger-ui:
    url: /openapi/backend-api.yaml
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://db:5432/db
    initialization-mode: always
  devtools:
    add-properties: false
