server:
  port: 8080
  ssl:
    enabled: false
springdoc:
  swagger-ui:
    url: /openapi/backend-api.yaml
spring:
  datasource:
    platform: postgres
    initialization-mode: always
  devtools:
    add-properties: false
